### ISSUE TITLE
regarding the plot of "predicted" and the plot of "prediction porba.."

### ISSUE THREAD

**Issue by surfreta** [julienr/kaggle_uns#1]
Hi Julien,

Thanks for sharing your code for Kaggle competition. I am kind of confusion about some plot you generated during the training process, such as the following one.

What's the different between the plot of "predicted" and the plot of "prediction proba ...". Looks like the third plot (titled as predicted) does not get the mask while the fourth one get something similar to mask.

Thanks.

![capture](https://cloud.githubusercontent.com/assets/23064201/20335327/62a8a1ce-ab87-11e6-8c7d-b42a904b2a21.JPG)

**Comment by julienr** [comment]
So _predicted_ is a thresholded version of _prediction proba_. The threshold is a parameter and I think I usually used something close to 0.4-0.6. So in this case, the model had to little confidence in its prediction for the mask to be trusted and therefore the image was labelled as no mask.

I bet you can find smarter ways to convert from probability image to binary image. Here I'm doing it per pixel, but maybe a global prediction likelihood computed from all pixels would be better. This is definitely something that can be improved.

**Comment by surfreta** [comment]
Hi Julienr,

Thanks for the explanation.  I  posted a question on stackoverflow regarding the observations I made during the training process. Would you like to take a look at it, and see whether you can share any insight?

Thanks.

http://stackoverflow.com/questions/40640906/the-prediction-figures-i-got-during-training-a-semantic-segmentation-model

**Comment by julienr** [comment]
I added a comment on stackoverflow. Let's continue this discussion there.

**Comment by surfreta** [comment]
Hi Julien,

I have updated the code and model I used for the ultrasound nerve
segmentation.

Would you like to take a look at it and see what might be go wrong for the
training process? Thanks.

http://stackoverflow.com/questions/40640906/the-prediction-figures-i-got-during-training-a-semantic-segmentation-model
